= Extending Vim
:stylesdir: css
:stylesheet: style.css
:imagesdir: images
:scriptsdir: javascript
:linkcss:
:toc:

You should know the mantra by now: "`Vim does a lot by itself`". But Vim doesn't do _everything_ and, sometimes, we would like it to do what it does in a slightly different way.

== Vimscript

=== Functions

=== Commands

=== Variables

=== Etc.

== Good practices

== Plugins

A "`Plugin`" is one or more scripts written by other Vimmers to extend Vim in one way or another. Some plugins may add support for a language not supported by Vim natively. Some plugins may provide a more useable abstraction over a built-in feature. Some plugins may give you a nice colorscheme. Some plugins may provide no benefit whatsoever. Some plugins... Well there are _thousands_ of them.

=== When to look for plugins

For the self-respecting Patient Vimmer, installing a third-party plugin should be the last resort. Not because plugins are antiethical or whatever but because there's more often than not a built-in way to do what you want and/or a built-in way to customize Vim to do what you want.

In my opinion, Vimmers should look

=== Where to look for plugins

=== Installing plugins

==== Manually

==== Vimball

==== Pathogen

==== Vundle

==== Neobundle

==== VAM

==== Plug

==== Packages

==== Notes on Git/Mercurial…

=== Updating plugins

=== Removing plugins

++++
<div id="nav" class="toc">
<p>Where to go now?</p>
<ul class="sectlevel1">
<li><a href="#">foo</a></li>
<li><a href="#">bar</a></li>
<li><a href="#">baz</a></li>
</ul>
<div id="bottom">
<p>Written by <a href="https://github.com/romainl">Romain Lafourcade</a>, with help from <a href="https://github.com/dahu/">Barry Arthur</a> and the #vim community.</p>
<p class="copyleft">Copyleft 2015</p>
</div>
</div>
<script src="javascript/behavior.js"></script>
++++
